workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

pages:
  script:
    - cd workflow/docs
    - make html
    - mv build/html ../../public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
