workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

pages:
  script:
    - mkdir public
    - cp -r workflow/docs/build/html public  
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
