workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

pages:
  script:
    - cd workflow/docs
    - make
    - mv build ../../public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
