workflow:
  rules:
    - if: '$CI_COMMIT_BRANCH'

pages:
  script:
    - conda env create --file workflow/envs/doc.yml --name shape-ce-doc || 0
    - conda activate shape-ce-doc
    - cd workflow/docs
    - make html
    - mv build/html ../../public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
