channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake >=5.24.1
  - jupyterlab
  - voila
  - ipywidgets
  - ipyfilechooser
  - mamba
  - fire
  - pandas
  - numpy
  - matplotlib
  - scikit-bio
  - scipy
  - viennarna
  - openjdk
  - pip
  - ruamel.yaml
  - pip: 
    - bsddb3 
    - ipanemap
