# This file should contain everything to configure the workflow on a global scale.

###
# path to the samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas and opened by
# libreoffice and excel
samples: "config/samples.tsv"

## General Workflow configuration ##

### 
# List of studied RNA, with an identifier, and the corresponding fasta file
# The fasta file should contain a description line containing the origin of the sequence (sequence database) with its unique identifier
# all "rna_id" column value in samples.tsv must have a corresponding line in this section.
sequences:
  gltB2: "resources/gltB2.fa"

###
# List each condition here, each item in this line must correspond to a column of the samples.tsv file, and be also putted into format -> condition
conditions:
  - probe
  - interaction
  - magnesium


###
# Allow snakemake to import automatically external files
# Not fully tested yet
allow_auto_import: True

###
# filename and titles formatting 
format:
  ###
  # Format of the conditions, will be use to identify sample and construct filename.
  # All variable conditions should be referenced here
  # Name of the conditions must correspond a column header in the samples.tsv file
  condition: "{probe}_{interaction}_{magnesium}"
  ###   
  # Same as condition but for control data. {control} will be replaced by the rawdata->control variable content 
  control_condition: "{control}_of_{probe}_{interaction}_{magnesium}"
  ###
  # Format use to create comprehensible Snakemake message when running workflow. conditions must be prefixed with "wildcards."
  message: "{wildcards.rna_id} with {wildcards.probe} with {wildcards.interaction} {wildcards.magnesium}"

###
# Information concerning raw datas
rawdata:
  ###
  # Path to the folder containing Raw experimental data, it will be prefixed to "control_file" and "probe_file"
  path_prefix: "../../biodata"
  ###
  # Type of the raw data. It will establish the starting point of the pipeline. Either from file directly from the sequencer or already converted to csv.
  type: "fluo-ceq8000" # ["fluo-ceq8000", "fluo-ce"]
  ###
  # Name of the control 
  control: "DMSO"

## Steps configurations ##

###
# QuShape project generator & extractor
qushape:
  ###
  # Definition of sequencer channels used for this project
  channels:
    RX: 0 # Channel 1
    RXS1: 2 # Channel 3
    BG: 0 # Channel 1
    BGS1: 2 # Channel 3
  ###
  # Used ddNTP 
  ddNTP: ddA

### Reactivity Normalization ###
normalization:
  # Which nucleotide are reactive to the shape probe
  reactive_nucleotides: ["A", "C", "G", "U"]
  # All value above this percentile are considered as outliers, preliminarly to all other treatments.
  stop_percentile: 90. 
  # Value below this threshold are considered non-reactive (0.0)
  low_norm_reactivity_threshold: -0.3
  # Which normalizations methods will be used, several are accepted. Autorized values are : simple, interquartile
  norm_methods:
    - simple
    - interquartile
  # oulier threshold for simple normalization method
  simple_outlier_percentile: 98.
  # percentile of values averaged to create the normalization term
  simple_norm_term_avg_percentile: 90.

### Replicate Aggregation
aggregate:
  norm_method: simple # or interquartile 
  
  # You can specify the name of the column used for normalization instead of the normalization method 
  #norm_column: "simple_norm_reactivity" #  
  min_ndata_perc: 0.5
  min_nsubdata_perc: 0.66
  max_mean_perc: 0.682
  min_dispersion: 0.05

### IPANEMAP ###
ipanemap:
  pools:
    - id: 1M7_Mg_none
      rna_id: gltB2
      conditions:
        - interaction: none
          magnesium: noMg
          probe: 1M7
  sampling:
    enable: True
    nstructures: 1000
    temperature: 37
    m: 1.3
    b: -0.4
  clustering:
    max_diameter_threshold: 7
    max_avg_diameter_threshold: 7
  pareto:
    percentage: 20
    zcutoff: 0.05
  visualization:
    draw_models: True
    draw_centroids: True
    show_probing: True

## Others configurations ## 

# Folder names 
folders:
  fluo-ceq8000: 1.1-fluo-ceq8000
  fluo-ce: 1.2-fluo-ce
  qushape: 2-qushape
  reactivity: 3.1-reactivity
  normreact: 3.2-normreact
  aggreact: 4.1-aggreact
  aggreact-ipanemap: 4.2-aggreact-ipanemap  
  ipanemap-config: 5.1-ipanemap-config
  ipanemap-out: 5.2-ipanemap-out
  structure: 5.3-structure
  varna: 5.4-varna
